### ISSUE TITLE
Can you please add supported language code to the get v2 config rest api?

### ISSUE THREAD

**Issue by Romick2005** [TartuNLP/translation-api#2]
Currently https://api.tartunlp.ai/translation/docs#/v2/get_config_v2_get returns only language pairs.
```
{
  "xml_support": true,
  "domains": [
    {
      "name": "General",
      "code": "general",
      "languages": [...]
    },
    {
      "name": "Legal",
      "code": "legal",
      "languages": [
        "est-eng",
        "eng-est",
        "ger-est",
        "rus-est",
        "est-ger",
        "est-rus"
      ]
    }
  ]
}
```

Would be great to have languageCodes also as a field. Similar to this [list](https://github.com/TartuNLP/translation-api/blob/main/config/config.yaml#L23C1-L23C15)

**Comment by Romick2005** [comment]
Is it possible to have eng-ukr as supported language translation, but do not have ukr-eng for example?

**Comment by liisaratsep** [comment]
Hi, can you elaborate a bit on the use case for this request? We accept standard 2-letter and 3-letter ISO language code formats, there are even libraries to automatically convert these. The mapping in our config file is to handle internal workflows when processing the request, it is not really informative to the end user.

> Is it possible to have eng-ukr as supported language translation, but do not have ukr-eng for example?

Yes, only specific combinations (and directions) may be available in some cases which is why they are specified all separately in such a long list.
